erDiagram
    usuario ||--o{ denuncia : registra
    usuario }o--|| perfil_acesso : possui
    denuncia }o--|| categoria : classificada_em
    denuncia ||--o{ historico_status : possui_timeline

    usuario {
        int idUsuario PK
        string nome
        string email
        string senha_hash
        int idPerfil FK
        date dtCriacao
        boolean ativo
    }

    perfil_acesso {
        int idPerfil PK
        string nomePerfil
        string permissoes
    }

    denuncia {
        int idDenuncia PK
        int idUsuario FK
        int idCategoria FK
        string fotoUrl
        float latitude
        float longitude
        string descricao
        string status
        date dtCriacao
        date dtResolucao
    }

    categoria {
        int idCategoria PK
        string nome
        string icone
        int prazoResolucao
    }

    historico_status {
        int idHistorico PK
        int idDenuncia FK
        string statusAnterior
        string statusNovo
        datetime dtAlteracao
        int idResponsavel
    }
